apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webhook-dispatcher
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert.gardener.cloud/issuer: {{ .Values.ingress_issuer_name }},
    cert.gardener.cloud/purpose: managed,
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: {{ .Values.ingress_host }}
    dns.gardener.cloud/ttl: "{{ .Values.ingress_ttl }}"
spec:
  rules:
  - host: {{ .Values.ingress_host }}
    http:
      paths:
      - backend:
          serviceName: webhook-dispatcher-svc
          servicePort: 80
  - host: {{ .Values.external_url }}
    http:
      paths:
      - backend:
          serviceName: webhook-dispatcher-svc
          servicePort: 80
  tls:
  - hosts:
{{- range $host := .Values.ingress_tls_hosts }}
    - "{{ $host }}"
{{- end }}
    secretName: webhook-dispatcher-tls
